#!/bin/bash
#
# Author:  Ben_Podawiltz
# Script:  ops-challenge-03
# Revision:  4.22.21
#########################

# Purpose:  
# Create a bash script that alters file permissions of everything in a directory.
# 1. Prompts user for input directory path.
# 2. Prompts user for input permissions number (e.g. 777 to perform a chmod 777)
# 3. Navigates to the directory input by the user and changes all files inside it to the input setting.
# 4. Prints to the screen the directory contents and the new permissions settings of everything in the directory.

################################################

# Globals:



################################################

#Script

echo -e "\nEverything in current directory"     
echo -e "\n*******************************"
ls -la  #displays contents of current directory as a reminder of where the user is

echo -e "\nPlease enter directory full path in this format [/home/user/dir1/dir2...etc] to change permissions"
read dir_path  #stores directory path

echo -e "\nPlease enter permissions for $dir_path:"  #calls directory path
read per_num  #stores permissions input from user

############################################

# Functions:

perm_setting () {
    if cd $dir_path
    then
        chmod -R $per_num $dir_path *  #changes user input permission recursively in user input pathway 
    fi
}

####################################

echo -e "\nNavigating to $dir_path"
echo -e "\n***********************"
cd $dir_path
ls -la  #this command is listing the previous run output (?)

###################################

# Call the function

perm_setting
####################################

# Comment: 
# I could not get the sub directory to change permissions despite using the arguement -R after
# chmod. Also the output of ls -laIt will be fun to play with this script as there are many oppportunities to expand its potential.

####################################

# Sources: https://stackoverflow.com/questions/29691344/shell-prompt-user-to-enter-a-directory-path


#End